version: '3'
services:
  mongo1:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - C:/MongoDockerData/mongo1:/data/db
    command: --replSet rs0

  mongo2:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - C:/MongoDockerData/mongo2:/data/db
    command: --replSet rs0

  mongo3:
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - C:/MongoDockerData/mongo3:/data/db
    command: --replSet rs0